services:
  producer:
    depends_on:
      - kafka-init
      - kafka
      - post-filter
    build: producer/
    container_name: producer
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      KAFKA_BROKER: kafka:9092
      # KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_OUTPUT_TOPIC: llm-posts
    restart: unless-stopped
    volumes:
      - producer_data:/app/data

  post-filter:
    build: ./post-filter/
    container_name: llm-classifier
    ports:
      - "8002:8000"
    restart: unless-stopped
    # The 'environment' section for the token has been removed.
    volumes:
      - huggingface_cache:/root/.cache/huggingface

  enrichment-agent:
    depends_on:
      - kafka-init
      - qdrant
      - postgres
    build: ./enrichment-agent/
    container_name: enrichment-agent
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      QDRANT_HOST: http://qdrant:6333
      KAFKA_BROKER: kafka:9092
      TOPIC_NAME: llm-posts
      OUTPUT_TOPIC: llm-embeddings-enriched
      GEMINI_KEY: ${GEMINI_KEY}
      MISTRAL_KEY: ${MISTRAL_KEY}
    restart: unless-stopped

  trend-processor-agent:
      depends_on:
        - kafka-init
        - kafka
        - enrichment-agent
        - postgres
      build: ./trend-processor-agent/
      container_name: trend-processor-agent
      environment:
        LOG_LEVEL: ${LOG_LEVEL}
        KAKFA_BROKER: kafka:9092
        TOPIC_NAME: enriched-llm-posts
        DATABASE_HOST: postgres
        DATABASE_NAME: ${POSTGRES_DB}
        DATABASE_USER: ${POSTGRES_USER}
        DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
        DATABASE_PORT: 5432
        INPUT_TOPIC: llm-embeddings-enriched
      restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped


  frontend:
    build: ./webapp/frontend/
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
      - qdrant
    restart: unless-stopped
    volumes:
      - ./webapp/frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    ports:
      - "3001:3000"
    restart: unless-stopped


  kafka:
      build: kafka/
      container_name: kafka
      ports:
        - "9092:9092"
        - "9093:9093"
        - "29092:29092"
      environment:
        # Kafka KRaft Config
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
        KAFKA_NODE_ID: 1
        KAFKA_PROCESS_ROLES: broker,controller
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_NUM_PARTITIONS: 1
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      restart: unless-stopped


  kafka-init:
    image: apache/kafka:3.7.0
    depends_on:
      - kafka
    entrypoint: [ "sh", "-c" ]
    command: >
      "
      echo 'Waiting for Kafka to be ready...' &&
      while ! nc -z kafka 9092; do sleep 1; done &&
      echo 'Kafka is up. Creating topics...' &&
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic __consumer_offsets --partitions 20 --replication-factor 1 &&
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic llm-posts --replication-factor 1 --partitions 1 &&
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic llm-embeddings-enriched --replication-factor 1 --partitions 1 &&
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic llm_training_data_raw --replication-factor 1 --partitions 1
      "

  kafka-ui:
    container_name: kafka-ui
    depends_on:
      - kafka
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - AUTH_TYPE="LOGIN_FORM"
      - SPRING_SECURITY_USER_NAME=${KAFKA_UI_LOGIN}
      - SPRING_SECURITY_USER_PASSWORD=${KAFKA_UI_PASSWORD}
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333" # HTTP/REST API & Web UI
      - "6334:6334" # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  mongo:
    profiles: ["optional"]
    image: mongo:latest
    container_name: mongo

    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mongo-express:
    profiles: ["optional"]
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  qdrant_storage:
  postgres_data:
  producer_data:
  pgadmin_data:
  grafana_data:
  huggingface_cache: {}
  mongo_data:
