global:
  scrape_interval: 15s
# Monitoring producer
scrape_configs:
  - job_name: 'producer'
    static_configs:
      - targets: ['producer:8000']

# Monitoring enrichment-agent
scrape_configs:
  - job_name: 'enrichment-agent'
    static_configs:
      - targets: ['enrichment-agent:8000']
      
# Monitoring Kafka
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:7071']